import React, { createContext, useContext, useState, useEffect } from 'react'

const TRANSLATIONS = {
  en: {
    // Header
    searchPlaceholder: 'Search catering, decoration, photography, packages...',
    searchServicesOrVendors: 'Search services or vendors...',
    search: 'Search',
    changeLocation: 'Change',
    savedVendors: 'Saved Vendors',
    myBookings: 'My Bookings',
    myProfile: 'My Profile',
    switchLanguage: 'Language: English / தமிழ்',

    // Home
    heroTitle: 'Plan your perfect',
    heroEvent: 'event.',
    heroSubtitle: 'Find catering, decoration, photography, mehendi, jewellery, music and everything else you need — all from verified local providers.',
    eventLocation: 'Event location',
    searchBtn: 'Search',
    exploreServices: 'Explore Services',
    exploreServicesSub: 'Find top-rated individual services for your event.',
    explorePackages: 'Explore Packages',
    explorePackagesSub: 'Complete celebration bundles, expertly curated.',
    findLabour: 'Find Event Labour',
    findLabourSub: 'Book trained staff to set up and manage your event.',
    popularServices: 'Popular services',
    popularServicesSub: 'Browse categories and book verified specialists',
    popularPackages: 'Popular packages',
    popularPackagesSub: 'Ready-made celebration options tailored for your event',
    popularProviders: 'Popular Companies',
    popularProvidersSub: 'Top rated event companies and experienced vendors',
    viewAll: 'View all',
    startingPrice: 'Starting price',
    reviews: 'reviews',
    events: 'events',

    // Service Categories (Simple & Village-Friendly)
    All: 'All',
    Catering: 'Catering / Food',
    Decoration: 'Decoration',
    Photography: 'Photography',
    Videography: 'Videography',
    Mehendi: 'Mehendi',
    Jewellery: 'Jewellery',
    Mandapam: 'Mandapam',
    'Music & DJ': 'DJ & Mic Set',
    Tailoring: 'Tailoring',
    Makeup: 'Makeup',
    Flowers: 'Flowers',
    Furniture: 'Chairs & Tables',
    'Beauty & Spa': 'Beauty Care',
    'Panthal & Tent': 'Panthal',
    'Sweets & Desserts': 'Sweets & Snacks',
    'Water Supply': 'Water Can Supply',
    'Event Staff': 'Helpers & Servers',
    'Priest & Rituals': 'Iyer / Priest',
    Invitations: 'Patrikai / Cards',
    Transport: 'Car & Van Rental',
    Nadaswaram: 'Nadaswaram / Melam',
    'Chenda Melam': 'Chenda Melam',
    'Return Gifts': 'Thamboolam Bags',
    'Seer Plates': 'Seer Thattu',
    Kolam: 'Kolam',
    'Muhurtham Malai': 'Malai',
    'Live Stalls': 'Food Stalls',
    'Special Effects': 'Entry Fireworks',
    'Audio Visual': 'LED Screen',
    Generator: 'Generator',
    'Valet Parking': 'Parking Helpers',
    Security: 'Security',

    // Package Categories
    'All Packages': 'All Packages',
    Wedding: 'Wedding',
    Birthday: 'Birthday',
    Reception: 'Reception',
    Engagement: 'Engagement',
    'Baby Shower': 'Baby Shower',
    Corporate: 'Corporate',
    Anniversary: 'Anniversary',
    Housewarming: 'Housewarming',
    Upanayanam: 'Upanayanam & Sacred Thread',
    Sashtiapthapoorthi: 'Sashtiapthapoorthi (60th Kalyanam)',
    'Ear Piercing': 'Ear Piercing (Kaadhu Kuthu)',
    'Puberty Ceremony': 'Puberty / Half Saree Ceremony',
    'Festival & Pooja': 'Festival & Vedic Pooja',
    packagesTitle: 'Curated Celebration Packages',
    packagesSubtitle: 'All-inclusive, stress-free event packages customized for memorable occasions.',
    viewPackageDetails: 'View Package Details',
    whatsIncluded: "What's included:",
    servicesIncluded: 'Services included',

    // Labour & Staff Support
    eventSupportStaff: 'Event Support Staff',
    labourTitle: 'Event Staff & Labour Support',
    labourSubtitle: 'Book trained event staff for smooth catering, setup, hospitality and cleanup.',
    allLabour: 'All Labour',
    'All Labour': 'All Labour',
    'Food Servers': 'Food Servers',
    'Cleaning Staff': 'Cleaning Staff',
    'Setup Crew': 'Setup Crew',
    'Event Helpers': 'Event Helpers',
    'Panthal Staff': 'Panthal Staff',
    'Hospitality Staff': 'Hospitality Staff',
    'Food & Panthi Servers': 'Food & Panthi Servers',
    'Kitchen Helpers & Cutters': 'Kitchen Helpers & Cutters',
    'Dishwashers & Vessel Cleaners': 'Dishwashers & Vessel Cleaners',
    'Panthal & Shamiana Riggers': 'Panthal & Shamiana Riggers',
    'Setup & Furniture Crew': 'Setup & Furniture Crew',
    'Valet Parking & Marshals': 'Valet Parking & Marshals',
    'Security & Bouncers': 'Security & Bouncers',
    'Hospitality & Thamboolam Staff': 'Hospitality & Thamboolam Staff',
    'Luggage & Room Attendants': 'Luggage & Room Attendants',
    'Sound, Light & Generator Crew': 'Sound, Light & Generator Crew',
    'Flower & Garland Helpers': 'Flower & Garland Helpers',
    'Pooja & Homam Assistants': 'Pooja & Homam Assistants',
    foodServers: 'Food Servers',
    cleaningStaff: 'Cleaning Staff',
    setupCrew: 'Setup Crew',
    eventHelpers: 'Event Helpers',
    panthalStaff: 'Panthal Staff',
    hospitalityStaff: 'Hospitality Staff',
    fromPrice: 'From',
    perStaff: '/ staff',
    dailyShiftRate: 'Daily Shift Rate',
    responsibilitiesInclusions: 'Staff Responsibilities & Inclusions',
    shiftGuidelines: 'Shift & Booking Guidelines',
    standardShift: 'Standard Shift',
    standardShiftVal: '8 Hours Duration',
    overtimeBilling: 'Overtime Billing',
    overtimeBillingVal: '1.5x Hourly Rate',
    cancellationPolicy: 'Cancellation Policy',
    cancellationPolicyVal: 'Free before 48 hours',
    managedBy: 'Managed by',
    guaranteeTitle: 'rjpm.in Staffing Guarantee',
    guaranteeDesc: '100% verified crew with emergency replacements guaranteed within 60 minutes in case of absence.',

    // Common Actions & Badges
    call: 'Call',
    callAgency: 'Call Agency',
    callProvider: 'Call Provider',
    chatWhatsApp: 'Chat on WhatsApp',
    whatsapp: 'WhatsApp',
    viewDetails: 'View Details',
    details: 'Details',
    verified: 'Verified',
    verifiedAgency: 'Verified Agency',
    popular: 'Popular',
    instantBooking: 'Instant staffing booking available',
    backToLabour: 'Back to labour support',
    backToPackages: 'Back to packages',
    backToProvider: 'Back to provider',

    // Filters
    nearMe: 'Near me',
    price: 'Price',
    rating4Plus: '4+ Rating',
    moreFilters: 'More filters',
    clearFilter: 'Clear filter',
    resetFilters: 'Reset all filters',
    smartFilter: 'Smart Filter',
    smartFilterActive: 'Smart Filter Active',
    editFilter: 'Modify',
    clear: 'Clear',
    allVerifiedProviders: 'All verified providers near you',
    allEventServices: 'All Event Services',
    servicesNearYou: 'services near you',
    providersNearYou: 'providers near you',

    // Profile Page
    myAccount: 'My Account',
    accountSubtitle: 'Manage your personal details, celebration bookings, and city preferences.',
    signInTitle: 'Sign in to rjpm.in',
    signInSubtitle: 'Access your celebration quotes, booked vendors, and saved preferences.',
    continueMobileOTP: 'Sign In with Mobile',
    signInButton: 'Sign In with Mobile',
    bookingsAndEnquiries: 'My Bookings & Enquiries',
    savedVendorsAndPackages: 'Saved Vendors & Packages',
    languageSetting: 'Language / மொழி',
    notificationsAlerts: 'Notifications & Alerts',
    preferencesEventTypes: 'Preferences & Event Types',
    helpSupport: 'Help & Customer Support',
    logOut: 'Log Out',
    eventHost: 'rjpm.in Host',

    // Bookings Page
    bookingsTitle: 'My Bookings & Enquiries',
    bookingsSubtitle: 'Keep track of all your event services, confirmations, and discussions.',
    tabAll: 'All',
    tabPending: 'Pending',
    tabAccepted: 'Confirmed',
    tabCompleted: 'Completed',
    tabCancelled: 'Cancelled',
    noBookingsFound: 'No bookings found',
    noBookingsSubtitle: 'You have not made any bookings in this section yet.',
    exploreServicesBtn: 'Explore Event Services',

    // Favorites Page
    favoritesTitle: 'Saved Vendors & Services',
    favoritesSubtitle: 'Providers and celebration packages you have shortlisted for your special event.',
    emptyFavoritesTitle: 'Your shortlist is empty',
    emptyFavoritesSubtitle: 'Tap the heart icon on any vendor, service, or package to save it here for easy comparison.',
    exploreVendorsBtn: 'Explore Event Vendors',

    // Location Modal
    selectLocation: 'Select Celebration Location',
    exploreArea: 'Explore verified vendors and services in your area.',
    locationPlaceholder: 'Enter city or area (e.g. PACR Salai, Rajapalayam)',
    apply: 'Apply',
    popularAreas: 'Popular Rajapalayam Areas',

    // Provider Detail
    back: 'Back',
    loadingProvider: 'Loading provider profile...',
    providerNotFound: 'Provider Not Found',
    browseProviders: 'Browse Providers',
    verifiedProvider: 'Verified Provider',
    registeredProvider: 'Registered Provider',
    yearsExperience: 'experience',
    eventsCompleted: 'completed',
    aboutProvider: 'About',
    defaultAbout: "One of Rajapalayam's premier event specialists with extensive experience in weddings, receptions, and corporate celebrations. Renowned for authentic flavours, hygienic execution, stunning thematic decor, and courteous hospitality staff.",
    servicesOffered: 'Services Offered',
    servicesCount: 'services',
    noServicesCategory: 'No services in this category.',
    curatedPackagesCount: 'Curated Packages',
    customerReviewsCount: 'Customer Reviews',
    noReviewsYet: 'No reviews yet. Be the first to review after your event!',
    noRatingsYet: 'No ratings yet',
    beFirstToRate: 'Be the first to rate',
    rateThisProvider: 'Rate this Provider',
    rateThisService: 'Rate this Service',
    yourRating: 'Your Rating',
    ratingSubmitted: 'Thank you for your rating!',
    signInToRate: 'Please sign in to rate',
    tapToRate: 'Tap stars to rate',
    recentCelebration: 'Recent Celebration',
    verifiedHost: 'Verified Host',
    responseFrom: 'Response from',
    providerInformation: 'Provider Information',
    yearsInIndustry: 'Years in Event Industry',
    documentVerified: 'Document & Identity Verified',
    respondsWithin: 'Usually responds within 2 hours',
    successfulGatherings: 'Successful Gatherings',
    serviceLocalities: 'Service Localities',
    allLocalities: 'All Rajapalayam Areas',
    allChennaiLocalities: 'All Rajapalayam Areas',
    checkAvailability: 'Check Date Availability',
    checkAvailabilityDesc: 'Select your wedding, birthday, or celebration date to verify open booking slots.',
    shareProfile: 'Share Profile',
    saveVendor: 'Save Vendor',
    profileLinkCopied: 'Provider profile link copied!',
    connectingCall: 'Connecting call to provider...',

    // Mobile Bottom Nav
    navHome: 'Home',
    navExplore: 'Explore',
    navSaved: 'Saved',
    navBookings: 'Bookings',
    navProfile: 'Profile',
    myBookings: 'My Bookings & Quotes',

    // Service Detail
    loadingService: 'Loading service specs...',
    serviceNotFound: 'Service Not Found',
    browseAllServices: 'Browse All Services',
    serviceLinkCopied: 'Service link copied to clipboard!',
    serviceOverview: 'Service Overview',
    serviceHighlights: 'Key Highlights & Inclusions',
    vendorInformation: 'Vendor Information',
    viewFullProfile: 'View Full Profile',
    whatsIncludedTitle: "What's Included",
    consultationPlanning: 'Complimentary consultation & customized planning',
    uniformedCrew: 'Professionally uniformed and background-checked crew',
    setupCleanup: 'Complete on-site setup and post-event cleanup',
    onTimeGuarantee: 'On-time execution guarantee with dedicated lead coordinator',
    pricePerPlate: 'Price per plate',
    dailyRate: 'Daily rate',
    perPlate: ' / plate',
    perDay: ' / day',
    onwards: ' onwards',
    providedBy: 'Provided by',
    verifiedListing: 'Verified rjpm.in Listing',
    directPricingAssurance: 'Direct pricing with no middleman markup. 100% money-back booking assurance.',
    share: 'Share',

    // Package Detail
    loadingPackage: 'Loading package details...',
    packageNotFound: 'Package not found',
    packageOverview: 'Package Overview',
    includedServicesTitle: 'Services Included in This Package',
    selectEventDate: 'Select Event Date',
    packageInvestment: 'Package Investment',
    aboutThisPackage: 'About This Package',
    guestCapacity: 'Guest Capacity',
    flexibleCount: 'Flexible count',
    eventTypeLabel: 'Event Type',
    allCelebrations: 'All Celebrations',
    executionMode: 'Execution Mode',
    fullTurnkey: 'Full turnkey coordination',
    servicesIncludedInPackage: 'Services Included in this Package',
    viewSpecs: 'View Specs',
    instantPackageInquiry: 'Instant package inquiry available',
    eventlyGuarantee: 'rjpm.in Guarantee',
    packageGuaranteeDesc: 'Direct communication with the business owner, verified service listings, and milestone-based peace of mind.',
    packageLinkCopied: 'Package link copied to clipboard!',
  },

  ta: {
    // Header
    searchPlaceholder: 'கேட்டரிங், அலங்காரம், புகைப்படம், தொகுப்புகள் தேடுங்கள்...',
    searchServicesOrVendors: 'சேவைகள் அல்லது விற்பனையாளர்களைத் தேடுங்கள்...',
    search: 'தேடு',
    changeLocation: 'மாற்றுக',
    savedVendors: 'விருப்பங்கள்',
    myBookings: 'என் முன்பதிவுகள்',
    myProfile: 'சுயவிவரம்',
    switchLanguage: 'மொழி: தமிழ் / English',

    // Home
    heroTitle: 'உங்கள் சிறப்பான நிகழ்வை',
    heroEvent: 'திட்டமிடுங்கள்.',
    heroSubtitle: 'கேட்டரிங், அலங்காரம், புகைப்படம், மெஹந்தி, நகைகள் மற்றும் உங்களுக்குத் தேவையான அனைத்தும் — சரிபார்க்கப்பட்ட உள்ளூர் கலைஞர்களிடமிருந்து.',
    eventLocation: 'நிகழ்வு இடம்',
    searchBtn: 'தேடுக',
    exploreServices: 'சேவைகளை ஆராய்க',
    exploreServicesSub: 'உங்கள் நிகழ்வுக்கான சிறந்த தனிநபர் சேவைகளைக் கண்டறியுங்கள்.',
    explorePackages: 'தொகுப்புகளை ஆராய்க',
    explorePackagesSub: 'முழுமையான கொண்டாட்ட தொகுப்புகள், பிரத்யேகமாக அமைக்கப்பட்டவை.',
    findLabour: 'நிகழ்வு பணியாளர்கள்',
    findLabourSub: 'நிகழ்வை நிர்வகிக்க பயிற்சி பெற்ற பணியாளர்களை முன்பதிவு செய்யுங்கள்.',
    popularServices: 'பிரபலமான சேவைகள்',
    popularServicesSub: 'பிரிவுகளைப் பார்த்து சரிபார்க்கப்பட்ட நிபுணர்களை முன்பதிவு செய்யுங்கள்',
    popularPackages: 'பிரபலமான தொகுப்புகள்',
    popularPackagesSub: 'உங்கள் நிகழ்வுக்கு ஏற்ற தயார் கொண்டாட்ட தொகுப்புகள்',
    popularProviders: 'பிரபலமான நிறுவனங்கள்',
    popularProvidersSub: 'உயர்தர நிகழ்வு நிறுவனங்கள் மற்றும் அனுபவமிக்க வழங்குநர்கள்',
    viewAll: 'அனைத்தும் காண்க',
    startingPrice: 'தொடக்க விலை',
    reviews: 'மதிப்புரைகள்',
    events: 'நிகழ்வுகள்',

    // Service Categories (எளிய தமிழ் - கிராம மக்களுக்கு எளிதில் புரியும் பெயர்கள்)
    All: 'அனைத்தும்',
    Catering: 'சமையல் / கேட்டரிங்',
    Decoration: 'மேடை அலங்காரம்',
    Photography: 'போட்டோ',
    Videography: 'வீடியோ',
    Mehendi: 'மெஹந்தி',
    Jewellery: 'நகைகள்',
    Mandapam: 'மண்டபம்',
    'Music & DJ': 'மைக் செட் & DJ',
    Tailoring: 'தையல்',
    Makeup: 'மேக்கப்',
    Flowers: 'பூக்கள்',
    Furniture: 'நாற்காலி & மேஜை',
    'Beauty & Spa': 'அழகு கலை',
    'Panthal & Tent': 'பந்தல்',
    'Sweets & Desserts': 'இனிப்பு & பலகாரம்',
    'Water Supply': 'குடிநீர் கேன்',
    'Event Staff': 'பணியாளர்கள்',
    'Priest & Rituals': 'ஐயர் / புரோகிதர்',
    Invitations: 'பத்திரிக்கை',
    Transport: 'கார் / வேன் வாடகை',
    Nadaswaram: 'நாதஸ்வரம் / மேளம்',
    'Chenda Melam': 'செண்டை மேளம்',
    'Return Gifts': 'தாம்பூலப்பை & பரிசுகள்',
    'Seer Plates': 'சீர் தட்டு',
    Kolam: 'கோலம்',
    'Muhurtham Malai': 'மாலை',
    'Live Stalls': 'உணவு ஸ்டால்கள்',
    'Special Effects': 'என்ட்ரி பட்டாசு & புகை',
    'Audio Visual': 'LED ஸ்கிரீன்',
    Generator: 'ஜெனரேட்டர்',
    'Valet Parking': 'பார்க்கிங்',
    Security: 'பாதுகாப்பு',

    // Package Categories
    'All Packages': 'அனைத்து தொகுப்புகள்',
    Wedding: 'திருமணம்',
    Birthday: 'பிறந்தநாள்',
    Reception: 'வரவேற்பு',
    Engagement: 'நிச்சயதார்த்தம்',
    'Baby Shower': 'வளைகாப்பு',
    Corporate: 'கார்ப்பரேட்',
    Anniversary: 'ஆண்டுவிழா',
    Housewarming: 'கிரகப்பிரவேசம்',
    Upanayanam: 'உபநயனம் & பூணூல்',
    Sashtiapthapoorthi: 'மணிவிழா - 60',
    'Ear Piercing': 'காது குத்து விழா',
    'Puberty Ceremony': 'மஞ்சள் நீராட்டு விழா',
    'Festival & Pooja': 'திருவிழா & பூஜை',
    packagesTitle: 'பிரத்யேக கொண்டாட்ட தொகுப்புகள்',
    packagesSubtitle: 'மறக்கமுடியாத தருணங்களுக்கு ஏற்ப அமைக்கப்பட்ட அனைத்து உள்ளடக்கிய தொகுப்புகள்.',
    viewPackageDetails: 'தொகுப்பு விவரங்களை காண்க',
    whatsIncluded: 'உள்ளடக்கம்:',
    servicesIncluded: 'சேர்க்கப்பட்ட சேவைகள்',

    // Labour & Staff Support
    eventSupportStaff: 'நிகழ்வு ஆதரவு ஊழியர்கள்',
    labourTitle: 'நிகழ்வு ஊழியர்கள் & தொழிலாளர் ஆதரவு',
    labourSubtitle: 'சீரான கேட்டரிங், அமைப்பு, விருந்தோம்பல் மற்றும் துப்புரவுக்கு பயிற்சி பெற்ற ஊழியர்களை முன்பதிவு செய்யுங்கள்.',
    allLabour: 'அனைத்து ஊழியர்கள்',
    'All Labour': 'அனைத்து ஊழியர்கள்',
    'Food Servers': 'உணவு பரிமாறுவோர்',
    'Cleaning Staff': 'துப்புரவு ஊழியர்கள்',
    'Setup Crew': 'அமைப்பு குழு',
    'Event Helpers': 'நிகழ்வு உதவியாளர்கள்',
    'Panthal Staff': 'பந்தல் ஊழியர்கள்',
    'Hospitality Staff': 'விருந்தோம்பல் ஊழியர்கள்',
    'Food & Panthi Servers': 'வாழை இலை & பஃபே பரிமாறுவோர்',
    'Kitchen Helpers & Cutters': 'சமையல் உதவியாளர்கள் & காய் நறுக்குவோர்',
    'Dishwashers & Vessel Cleaners': 'பாத்திரம் & தட்டு கழுவுவோர்',
    'Panthal & Shamiana Riggers': 'பந்தல் & கூடார அமைப்பாளர்கள்',
    'Setup & Furniture Crew': 'மேடை & தளபாடங்கள் அமைப்பு',
    'Valet Parking & Marshals': 'வாகன நிறுத்துமிடம் & போக்குவரத்து',
    'Security & Bouncers': 'பாதுகாப்பு & பவுன்சர்கள்',
    'Hospitality & Thamboolam Staff': 'விருந்தினர் உபசரிப்பு & தாம்பூலம்',
    'Luggage & Room Attendants': 'அறை & உடைமை உதவியாளர்கள்',
    'Sound, Light & Generator Crew': 'ஒலி, ஒளி & ஜெனரேட்டர் உதவியாளர்கள்',
    'Flower & Garland Helpers': 'மலர் தொடுப்போர் & மாலை கட்டுவோர்',
    'Pooja & Homam Assistants': 'பூஜை & ஹோம உதவியாளர்கள்',
    foodServers: 'உணவு பரிமாறுவோர்',
    cleaningStaff: 'துப்புரவு ஊழியர்கள்',
    setupCrew: 'அமைப்பு குழு',
    eventHelpers: 'நிகழ்வு உதவியாளர்கள்',
    panthalStaff: 'பந்தல் ஊழியர்கள்',
    hospitalityStaff: 'விருந்தோம்பல் ஊழியர்கள்',
    fromPrice: 'தொடக்கம்',
    perStaff: '/ நபர்',
    dailyShiftRate: 'தினசரி ஷிப்ட் கட்டணம்',
    responsibilitiesInclusions: 'ஊழியர் பொறுப்புகள் & உள்ளடக்கம்',
    shiftGuidelines: 'ஷிப்ட் & முன்பதிவு வழிகாட்டுதல்கள்',
    standardShift: 'வழக்கமான ஷிப்ட்',
    standardShiftVal: '8 மணி நேர கால அளவு',
    overtimeBilling: 'கூடுதல் நேர கட்டணம்',
    overtimeBillingVal: '1.5x மணி நேர கட்டணம்',
    cancellationPolicy: 'ரத்து செய்யும் கொள்கை',
    cancellationPolicyVal: '48 மணி நேரத்திற்கு முன் இலவசம்',
    managedBy: 'நிர்வகிப்பது',
    guaranteeTitle: 'rjpm.in ஊழியர் உத்தரவாதம்',
    guaranteeDesc: '100% சரிபார்க்கப்பட்ட குழு. அவசரத் தேவைகளுக்கு 60 நிமிடங்களுக்குள் மாற்றுப் பணியாளர் உறுதி.',

    // Common Actions & Badges
    call: 'அழைக்க',
    callAgency: 'நிறுவனத்தை அழைக்க',
    callProvider: 'வழங்குநரை அழைக்க',
    chatWhatsApp: 'வாட்ஸ்அப்பில் பேசுக',
    whatsapp: 'வாட்ஸ்அப்',
    viewDetails: 'விவரங்களை காண்க',
    details: 'விவரங்கள்',
    verified: 'சரிபார்க்கப்பட்டது',
    verifiedAgency: 'சரிபார்க்கப்பட்ட நிறுவனம்',
    popular: 'பிரபலம்',
    instantBooking: 'உடனடி பணியாளர் முன்பதிவு வசதி',
    backToLabour: 'பணியாளர்கள் பக்கத்திற்கு திரும்புக',
    backToPackages: 'தொகுப்புகள் பக்கத்திற்கு திரும்புக',
    backToProvider: 'வழங்குநருக்கு திரும்புக',

    // Filters
    nearMe: 'அருகில்',
    price: 'விலை',
    rating4Plus: '4+ மதிப்பீடு',
    moreFilters: 'கூடுதல் வடிகட்டிகள்',
    clearFilter: 'வடிகட்டியை நீக்கு',
    resetFilters: 'அனைத்து வடிகட்டிகளையும் மீட்டமை',
    smartFilter: 'ஸ்மார்ட் வடிகட்டி',
    smartFilterActive: 'ஸ்மார்ட் வடிகட்டி செயலில் உள்ளது',
    editFilter: 'திருத்து',
    clear: 'அகற்று',
    allVerifiedProviders: 'அருகில் உள்ள சரிபார்க்கப்பட்ட நிறுவனங்கள்',
    allEventServices: 'அனைத்து நிகழ்வு சேவைகள்',
    servicesNearYou: 'சேவைகள் உங்கள் அருகில்',
    providersNearYou: 'வழங்குநர்கள் உங்கள் அருகில்',

    // Profile Page
    myAccount: 'என் கணக்கு',
    accountSubtitle: 'உங்கள் தனிப்பட்ட விவரங்கள், முன்பதிவுகள் மற்றும் நகர விருப்பங்களை நிர்வகிக்கவும்.',
    signInTitle: 'rjpm.in-இல் உள்நுழையவும்',
    signInSubtitle: 'உங்கள் கொண்டாட்ட மேற்கோள்கள், முன்பதிவு செய்த கலைஞர்கள் மற்றும் விருப்பங்களை அணுகவும்.',
    continueMobileOTP: 'மொபைல் மூலம் உள்நுழைக',
    signInButton: 'மொபைல் மூலம் உள்நுழைக',
    bookingsAndEnquiries: 'என் முன்பதிவுகள் & தொடர்புகள்',
    savedVendorsAndPackages: 'சேமிக்கப்பட்ட கலைஞர்கள் & தொகுப்புகள்',
    languageSetting: 'மொழி / Language',
    notificationsAlerts: 'அறிவிப்புகள் & செய்திகள்',
    preferencesEventTypes: 'விருப்பங்கள் & நிகழ்வு வகைகள்',
    helpSupport: 'உதவி & வாடிக்கையாளர் ஆதரவு',
    logOut: 'வெளியேறு',
    eventHost: 'நிகழ்வு அமைப்பாளர்',

    // Bookings Page
    bookingsTitle: 'என் முன்பதிவுகள் & தொடர்புகள்',
    bookingsSubtitle: 'உங்கள் அனைத்து நிகழ்வு சேவைகள், உறுதிப்படுத்தல்கள் மற்றும் கலந்துரையாடல்களைக் கண்காணிக்கவும்.',
    tabAll: 'அனைத்தும்',
    tabPending: 'நிலுவையில்',
    tabAccepted: 'உறுதிப்படுத்தப்பட்டது',
    tabCompleted: 'முடிவடைந்தது',
    tabCancelled: 'ரத்து செய்யப்பட்டது',
    noBookingsFound: 'முன்பதிவுகள் இல்லை',
    noBookingsSubtitle: 'இப்பிரிவில் இதுவரை எந்த முன்பதிவுகளும் இல்லை.',
    exploreServicesBtn: 'நிகழ்வு சேவைகளை காண்க',

    // Favorites Page
    favoritesTitle: 'சேமிக்கப்பட்ட நிறுவனங்கள் & சேவைகள்',
    favoritesSubtitle: 'உங்கள் சிறப்பு நிகழ்வுக்காக நீங்கள் தேர்வு செய்த வழங்குநர்கள் மற்றும் தொகுப்புகள்.',
    emptyFavoritesTitle: 'விருப்பப் பட்டியல் காலியாக உள்ளது',
    emptyFavoritesSubtitle: 'எளிதாக ஒப்பிட எந்தவொரு வழங்குநர், சேவை அல்லது தொகுப்பிலும் உள்ள இதயக் குறியீட்டைத் தட்டவும்.',
    exploreVendorsBtn: 'நிகழ்வு வழங்குநர்களை ஆராய்க',

    // Location Modal
    selectLocation: 'நிகழ்வு இடத்தை தேர்வு செய்யவும்',
    exploreArea: 'உங்கள் பகுதியில் உள்ள சரிபார்க்கப்பட்ட வழங்குநர்களைக் கண்டறியுங்கள்.',
    locationPlaceholder: 'நகரம் அல்லது பகுதியை உள்ளிடவும்...',
    apply: 'அமைக்க',
    popularAreas: 'பிரபலமான பகுதிகள்',

    // Provider Detail
    back: 'பின்செல்க',
    loadingProvider: 'நிறுவன சுயவிவரம் ஏற்றப்படுகிறது...',
    providerNotFound: 'வழங்குநர் கிடைக்கவில்லை',
    browseProviders: 'நிறுவனங்களை உலாவுக',
    verifiedProvider: 'சரிபார்க்கப்பட்ட நிறுவனம்',
    registeredProvider: 'பதிவுசெய்யப்பட்ட நிறுவனம்',
    yearsExperience: 'அனுபவம்',
    eventsCompleted: 'நிகழ்வுகள் நிறைவு',
    aboutProvider: 'பற்றி',
    defaultAbout: 'சென்னையின் முன்னணி நிகழ்வு நிபுணர்களில் ஒருவர். திருமணம், வரவேற்பு மற்றும் கார்ப்பரேட் நிகழ்வுகளில் சிறந்த அனுபவம் கொண்டவர். சுவை, சுகாதாரம் மற்றும் நேர்த்தியான அலங்காரத்திற்கு பெயர் பெற்றவர்.',
    servicesOffered: 'வழங்கப்படும் சேவைகள்',
    servicesCount: 'சேவைகள்',
    noServicesCategory: 'இப்பிரிவில் சேவைகள் எதுவும் இல்லை.',
    curatedPackagesCount: 'பிரத்யேக தொகுப்புகள்',
    customerReviewsCount: 'வாடிக்கையாளர் மதிப்புரைகள்',
    noReviewsYet: 'மதிப்புரைகள் இன்னும் இல்லை. உங்கள் நிகழ்வுக்குப் பிறகு முதல் மதிப்புரையை வழங்கவும்!',
    noRatingsYet: 'மதிப்பீடுகள் இன்னும் இல்லை',
    beFirstToRate: 'முதலில் மதிப்பிடவும்',
    rateThisProvider: 'வழங்குநரை மதிப்பிடவும்',
    rateThisService: 'சேவையை மதிப்பிடவும்',
    yourRating: 'உங்கள் மதிப்பீடு',
    ratingSubmitted: 'மதிப்பீட்டிற்கு நன்றி!',
    signInToRate: 'மதிப்பிட உள்நுழைக',
    tapToRate: 'மதிப்பிட நட்சத்திரங்களைத் தொடவும்',
    recentCelebration: 'சமீபத்திய கொண்டாட்டம்',
    verifiedHost: 'சரிபார்க்கப்பட்ட வாடிக்கையாளர்',
    responseFrom: 'பதில் அளித்தவர்',
    providerInformation: 'நிறுவன விவரங்கள்',
    yearsInIndustry: 'ஆண்டுகள் நிகழ்வுத் துறை அனுபவம்',
    documentVerified: 'ஆவணம் & அடையாளம் சரிபார்க்கப்பட்டது',
    respondsWithin: 'பொதுவாக 2 மணி நேரத்திற்குள் பதிலளிப்பார்',
    successfulGatherings: 'வெற்றிகரமான நிகழ்வுகள்',
    serviceLocalities: 'சேவை வழங்கப்படும் பகுதிகள்',
    allLocalities: 'அனைத்து ராஜபாளையம் பகுதிகளும்',
    allChennaiLocalities: 'அனைத்து ராஜபாளையம் பகுதிகளும்',
    checkAvailability: 'தேதி கிடைக்கும் தன்மையை அறியவும்',
    checkAvailabilityDesc: 'உங்கள் திருமணம், பிறந்தநாள் அல்லது கொண்டாட்ட தேதிக்கான முன்பதிவு நிலையை சரிபார்க்கவும்.',
    shareProfile: 'சுயவிவரத்தைப் பகிர்க',
    saveVendor: 'வழங்குநரைச் சேமிக்க',
    profileLinkCopied: 'சுயவிவர இணைப்பு நகலெடுக்கப்பட்டது!',
    connectingCall: 'வழங்குநரை அழைக்க இணைக்கப்படுகிறது...',

    // Mobile Bottom Nav
    navHome: 'முகப்பு',
    navExplore: 'ஆராய்க',
    navSaved: 'சேமித்தவை',
    navBookings: 'முன்பதிவுகள்',
    navProfile: 'சுயவிவரம்',
    myBookings: 'எனது முன்பதிவுகள்',

    // Service Detail
    loadingService: 'சேவை விவரங்கள் ஏற்றப்படுகின்றன...',
    serviceNotFound: 'சேவை கிடைக்கவில்லை',
    browseAllServices: 'அனைத்து சேவைகளையும் காண்க',
    serviceLinkCopied: 'சேவை இணைப்பு நகலெடுக்கப்பட்டது!',
    serviceOverview: 'சேவை கண்ணோட்டம்',
    serviceHighlights: 'முக்கிய சிறப்பம்சங்கள் & உள்ளடக்கம்',
    vendorInformation: 'வழங்குநர் தகவல்',
    viewFullProfile: 'முழு விவரங்களை காண்க',
    whatsIncludedTitle: 'உள்ளடக்கம்',
    consultationPlanning: 'இலவச ஆலோசனை & பிரத்யேக திட்டமிடல்',
    uniformedCrew: 'சீரான சீருடை அணிந்த தகுதியான பணியாளர்கள்',
    setupCleanup: 'நிகழ்விட அமைப்பு மற்றும் நிகழ்வுக்குப் பிந்தைய துப்புரவு',
    onTimeGuarantee: 'நேரத்திற்கு நிறைவு செய்யும் உத்தரவாதம் மற்றும் ஒருங்கிணைப்பாளர்',
    pricePerPlate: 'ஒரு இலை / தட்டு விலை',
    dailyRate: 'தினசரி கட்டணம்',
    perPlate: ' / இலை',
    perDay: ' / நாள்',
    onwards: ' முதல்',
    providedBy: 'வழங்குபவர்:',
    verifiedListing: 'சரிபார்க்கப்பட்ட rjpm.in சேவை',
    directPricingAssurance: 'இடைத்தரகர் இல்லாத நேரடி விலை. 100% நம்பகமான முன்பதிவு உத்தரவாதம்.',
    share: 'பகிர்க',

    // Package Detail
    loadingPackage: 'தொகுப்பு விவரங்கள் ஏற்றப்படுகின்றன...',
    packageNotFound: 'தொகுப்பு கிடைக்கவில்லை',
    packageOverview: 'தொகுப்பு கண்ணோட்டம்',
    includedServicesTitle: 'இத்தொகுப்பில் சேர்க்கப்பட்டுள்ள சேவைகள்',
    selectEventDate: 'நிகழ்வு தேதியைத் தேர்ந்தெடுக்கவும்',
    packageInvestment: 'தொகுப்பு கட்டணம்',
    aboutThisPackage: 'இந்த தொகுப்பு பற்றி',
    guestCapacity: 'விருந்தினர் எண்ணிக்கை',
    flexibleCount: 'விருப்பத்திற்கேற்ப',
    eventTypeLabel: 'நிகழ்வு வகை',
    allCelebrations: 'அனைத்து கொண்டாட்டங்கள்',
    executionMode: 'செயலாக்க முறை',
    fullTurnkey: 'முழுமையான ஒருங்கிணைப்பு',
    servicesIncludedInPackage: 'இத்தொகுப்பில் சேர்க்கப்பட்டுள்ள சேவைகள்',
    viewSpecs: 'விவரங்களை காண்க',
    instantPackageInquiry: 'உடனடி தொகுப்பு விசாரணை வசதி',
    eventlyGuarantee: 'rjpm.in உத்தரவாதம்',
    packageGuaranteeDesc: 'நிறுவன உரிமையாளருடன் நேரடி தொடர்பு, சரிபார்க்கப்பட்ட சேவைகள் மற்றும் நம்பகமான நிறைவு.',
    packageLinkCopied: 'தொகுப்பு இணைப்பு நகலெடுக்கப்பட்டது!',
  },
}

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('evently_language') || 'en'
  })

  useEffect(() => {
    localStorage.setItem('evently_language', language)
    document.documentElement.lang = language
  }, [language])

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'ta' : 'en'))
  }

  const t = (key, fallback = '') => {
    if (!key) return fallback || ''
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || fallback || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
